import type {
  Category,
  TaskItem,
  CalendarEvent,
  TodayStats,
  MatrixQuadrantType,
} from "@/features/todos/types";

// ── Categories ──────────────────────────────────────────────────────────────

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 1,
    name: "Work",
    colorCode: "#3b82f6",
    preferredStartTime: "09:00",
    preferredEndTime: "17:00",
  },
  {
    id: 2,
    name: "Personal",
    colorCode: "#10b981",
    preferredStartTime: null,
    preferredEndTime: null,
  },
  {
    id: 3,
    name: "Learning",
    colorCode: "#8b5cf6",
    preferredStartTime: "19:00",
    preferredEndTime: "21:00",
  },
  {
    id: 4,
    name: "Health",
    colorCode: "#14b8a6",
    preferredStartTime: "06:00",
    preferredEndTime: "07:30",
  },
];

// ── Helper to find category ─────────────────────────────────────────────────

function cat(id: number): Category {
  return MOCK_CATEGORIES.find((c) => c.id === id)!;
}

// ── Matrix Tasks (grouped by quadrant) ──────────────────────────────────────

export const MOCK_MATRIX_TASKS: Record<MatrixQuadrantType, TaskItem[]> = {
  "do-now": [
    {
      id: 101,
      categoryId: 1,
      category: cat(1),
      parentId: null,
      title: "Review Delta project documentation",
      description: null,
      position: 1,
      status: "TODO",
      isDone: false,
      priority: 4,
      energyRequired: 4,
      estimatedMinutes: 45,
      dueDate: new Date().toISOString().slice(0, 10) + "T14:00:00",
      createdAt: "2026-05-19T08:00:00",
    },
    {
      id: 102,
      categoryId: 1,
      category: cat(1),
      parentId: null,
      title: "Weekly team sync meeting",
      description: "Zoom call with engineering team",
      position: 2,
      status: "TODO",
      isDone: false,
      priority: 3,
      energyRequired: 3,
      estimatedMinutes: 60,
      dueDate: new Date().toISOString().slice(0, 10) + "T16:30:00",
      createdAt: "2026-05-19T08:00:00",
    },
  ],
  schedule: [
    {
      id: 201,
      categoryId: 1,
      category: cat(1),
      parentId: null,
      title: "Plan Q3 strategy roadmap",
      description: null,
      position: 1,
      status: "TODO",
      isDone: false,
      priority: 2,
      energyRequired: 5,
      estimatedMinutes: 120,
      dueDate: "2026-05-25T10:00:00",
      createdAt: "2026-05-18T08:00:00",
    },
    {
      id: 202,
      categoryId: 3,
      category: cat(3),
      parentId: null,
      title: "Read 2 chapters of UI/UX Design book",
      description: null,
      position: 2,
      status: "TODO",
      isDone: false,
      priority: 2,
      energyRequired: 2,
      estimatedMinutes: 90,
      dueDate: "2026-05-24T20:00:00",
      createdAt: "2026-05-18T08:00:00",
    },
  ],
  delegate: [
    {
      id: 301,
      categoryId: 1,
      category: cat(1),
      parentId: null,
      title: "Reply to partnership support emails",
      description: "Assigned to: Nam NV",
      position: 1,
      status: "TODO",
      isDone: false,
      priority: 3,
      energyRequired: 2,
      estimatedMinutes: 30,
      dueDate: "2026-05-21T12:00:00",
      createdAt: "2026-05-19T09:00:00",
    },
    {
      id: 302,
      categoryId: 2,
      category: cat(2),
      parentId: null,
      title: "Book flight tickets to Hanoi",
      description: null,
      position: 2,
      status: "TODO",
      isDone: false,
      priority: 2,
      energyRequired: 1,
      estimatedMinutes: 15,
      dueDate: "2026-05-22T18:00:00",
      createdAt: "2026-05-19T10:00:00",
    },
  ],
  eliminate: [
    {
      id: 401,
      categoryId: 2,
      category: cat(2),
      parentId: null,
      title: "Mindless social media browsing",
      description: null,
      position: 1,
      status: "BACKLOG",
      isDone: false,
      priority: 1,
      energyRequired: 1,
      estimatedMinutes: null,
      dueDate: null,
      createdAt: "2026-05-19T12:00:00",
    },
    {
      id: 402,
      categoryId: 2,
      category: cat(2),
      parentId: null,
      title: 'Reorganize "Random" folder on Desktop',
      description: null,
      position: 2,
      status: "BACKLOG",
      isDone: false,
      priority: 1,
      energyRequired: 1,
      estimatedMinutes: 20,
      dueDate: null,
      createdAt: "2026-05-19T12:00:00",
    },
  ],
};

// ── Board Tasks (grouped by status) ─────────────────────────────────────────

export const MOCK_BOARD_TASKS: Record<string, TaskItem[]> = {
  TODO: [
    {
      id: 501,
      categoryId: 1,
      category: cat(1),
      parentId: null,
      title: "Design mobile app UI",
      description: null,
      position: 1,
      status: "TODO",
      isDone: false,
      priority: 4,
      energyRequired: 5,
      estimatedMinutes: 180,
      dueDate: "2026-05-25T17:00:00",
      createdAt: "2026-05-18T08:00:00",
    },
    {
      id: 502,
      categoryId: 2,
      category: cat(2),
      parentId: null,
      title: "Write user guide documentation",
      description: null,
      position: 2,
      status: "TODO",
      isDone: false,
      priority: 2,
      energyRequired: 3,
      estimatedMinutes: 90,
      dueDate: "2026-05-28T17:00:00",
      createdAt: "2026-05-18T10:00:00",
    },
  ],
  DOING: [
    {
      id: 601,
      categoryId: 1,
      category: cat(1),
      parentId: null,
      title: "Code Kanban feature",
      description: null,
      position: 1,
      status: "DOING",
      isDone: false,
      priority: 3,
      energyRequired: 4,
      estimatedMinutes: 240,
      dueDate: "2026-05-24T17:00:00",
      createdAt: "2026-05-17T08:00:00",
    },
    {
      id: 602,
      categoryId: 1,
      category: cat(1),
      parentId: null,
      title: "Fix Matrix UI bugs",
      description: null,
      position: 2,
      status: "DOING",
      isDone: false,
      priority: 4,
      energyRequired: 4,
      estimatedMinutes: 60,
      dueDate: "2026-05-23T17:00:00",
      createdAt: "2026-05-19T08:00:00",
    },
  ],
  IN_REVIEW: [
    {
      id: 701,
      categoryId: 1,
      category: cat(1),
      parentId: null,
      title: "Check responsive layouts",
      description: null,
      position: 1,
      status: "IN_REVIEW",
      isDone: false,
      priority: 2,
      energyRequired: 3,
      estimatedMinutes: 45,
      dueDate: "2026-05-22T17:00:00",
      createdAt: "2026-05-16T08:00:00",
    },
    {
      id: 702,
      categoryId: 1,
      category: cat(1),
      parentId: null,
      title: "Review backend code",
      description: null,
      position: 2,
      status: "IN_REVIEW",
      isDone: false,
      priority: 2,
      energyRequired: 4,
      estimatedMinutes: 60,
      dueDate: "2026-05-22T17:00:00",
      createdAt: "2026-05-16T08:00:00",
    },
  ],
  DONE: [
    {
      id: 801,
      categoryId: 1,
      category: cat(1),
      parentId: null,
      title: "Setup CI/CD pipeline",
      description: null,
      position: 1,
      status: "DONE",
      isDone: true,
      priority: 3,
      energyRequired: 4,
      estimatedMinutes: 120,
      dueDate: "2026-05-20T17:00:00",
      createdAt: "2026-05-15T08:00:00",
    },
    {
      id: 802,
      categoryId: 3,
      category: cat(3),
      parentId: null,
      title: "Complete TypeScript course",
      description: null,
      position: 2,
      status: "DONE",
      isDone: true,
      priority: 2,
      energyRequired: 3,
      estimatedMinutes: 60,
      dueDate: "2026-05-19T17:00:00",
      createdAt: "2026-05-14T08:00:00",
    },
  ],
};

// ── Today stats ─────────────────────────────────────────────────────────────

export const MOCK_TODAY_STATS: TodayStats = {
  total: 12,
  completed: 8,
  overdue: 2,
};

// ── Upcoming events ─────────────────────────────────────────────────────────

export const MOCK_UPCOMING_EVENTS: CalendarEvent[] = [
  {
    id: 1,
    title: "Meet with partners",
    description: null,
    startAt: new Date().toISOString().slice(0, 10) + "T15:00:00",
    endAt: new Date().toISOString().slice(0, 10) + "T16:00:00",
    isRecurring: false,
    recurrenceRule: null,
    color: "#ef4444",
  },
  {
    id: 2,
    title: "Send weekly report",
    description: null,
    startAt: new Date().toISOString().slice(0, 10) + "T17:00:00",
    endAt: new Date().toISOString().slice(0, 10) + "T17:30:00",
    isRecurring: true,
    recurrenceRule: "weekly",
    color: "#3b82f6",
  },
  {
    id: 3,
    title: "Evening workout",
    description: null,
    startAt: new Date().toISOString().slice(0, 10) + "T18:30:00",
    endAt: new Date().toISOString().slice(0, 10) + "T19:30:00",
    isRecurring: true,
    recurrenceRule: "daily",
    color: "#14b8a6",
  },
];
