services:
  db:
    image: postgres:17-alpine
    container_name: my-pace-db
    env_file:
      - ./apps/my-pace-service/.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U my_pace -d my_pace_db"]
      interval: 10s
      timeout: 5s
      retries: 5



  api:
    build:
      context: ./apps/my-pace-service
    container_name: my-pace-api
    env_file:
      - ./apps/my-pace-service/.env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy


  web:
    build:
      context: ./apps/web-app
    container_name: my-pace-web
    env_file:
      - ./apps/web-app/.env
    environment:
      NEXT_TELEMETRY_DISABLED: "1"
      NEXT_PUBLIC_API_URL: "http://localhost:8080/api"
      API_URL: "http://api:8080/api"
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_started

volumes:
  db_data:

