spring:
  application:
    name: my-pace-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/my_pace_db}
    username: ${SPRING_DATASOURCE_USERNAME:my_pace}
    password: ${SPRING_DATASOURCE_PASSWORD:my_pace_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: 3600 # 1 hour in seconds
    refresh-token-expiration: 604800 # 7 days in seconds
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
