spring:
  application:
    name: my-pace-service
  datasource:
    url: jdbc:mysql://localhost:3306/my_pace_db
    username: root
    password: 22718451
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  jwt:
    access-token-expiration: 3600000 # 1 hour in milliseconds
    refresh-token-expiration: 604800000 # 7 days in milliseconds
    secret: ${JWT_SECRET}
